using Microsoft.CodeAnalysis;
using Xunit;

namespace PostQuantum.CryptographicBillOfMaterials.Analyzer.Tests;

/// <summary>
/// Behavioural tests for the analyzer: the in-editor surface must match the CLI engine — correct rule ids,
/// correct per-finding severity, and no noise on clean code.
/// </summary>
public class CryptoDiagnosticAnalyzerTests
{
    private const string VulnerableSource = """
        using System.Net.Http;
        using System.Security.Authentication;
        using System.Security.Cryptography;

        public static class Crypto
        {
            public static byte[] EncryptBadly(byte[] data)
            {
                using var aes = Aes.Create();
                aes.Mode = CipherMode.ECB;
                aes.Key = new byte[] { 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16 };
                using var enc = aes.CreateEncryptor();
                return enc.TransformFinalBlock(data, 0, data.Length);
            }

            public static RSA MakeKey() => RSA.Create(2048);
            public static byte[] Legacy(byte[] d) => MD5.HashData(d);
            public static byte[] Good(byte[] d) => SHA384.HashData(d);

            public static HttpClient Insecure()
            {
                var handler = new HttpClientHandler
                {
                    ServerCertificateCustomValidationCallback = (_, _, _, _) => true,
                    SslProtocols = SslProtocols.Tls,
                };
                return new HttpClient(handler);
            }
        }
        """;

    [Fact]
    public async Task VulnerableSample_ProducesExpectedRulesAndSeverities()
    {
        var diagnostics = await AnalyzerHarness.RunAsync(VulnerableSource);
        var ids = diagnostics.Select(d => d.Id).ToHashSet();

        // The high-signal rules must all fire.
        Assert.Contains("CBOM0002", ids); // RSA — quantum vulnerable
        Assert.Contains("CBOM0007", ids); // ECB mode
        Assert.Contains("CBOM0030", ids); // hardcoded key
        Assert.Contains("CBOM0041", ids); // cert validation disabled
        Assert.Contains("CBOM0010", ids); // hash usage (MD5 + SHA-384)
    }

    [Fact]
    public async Task RsaCreate_IsAQuantumVulnerableWarning()
    {
        var diagnostics = await AnalyzerHarness.RunAsync(VulnerableSource);
        Diagnostic rsa = Assert.Single(diagnostics, d => d.Id == "CBOM0002");
        Assert.Equal(DiagnosticSeverity.Warning, rsa.Severity);
        Assert.Equal(16, rsa.Line()); // RSA.Create(2048)
    }

    [Fact]
    public async Task HashRule_SeverityIsPerFinding_Md5Warning_Sha384Info()
    {
        // Regression guard: MD5 and SHA-384 share rule CBOM0010, but severity must reflect the per-finding
        // computed risk — broken MD5 is a warning, clean SHA-384 is a quiet informational hint. A single
        // rule-default severity would wrongly flatten both.
        var hashFindings = (await AnalyzerHarness.RunAsync(VulnerableSource))
            .Where(d => d.Id == "CBOM0010")
            .ToList();

        Assert.Contains(hashFindings, d => d.Severity == DiagnosticSeverity.Warning); // MD5
        Assert.Contains(hashFindings, d => d.Severity == DiagnosticSeverity.Info);     // SHA-384
    }

    [Theory]
    [InlineData("Payments.cs", "// <auto-generated/>\n")]   // header only — filename gives no cue at all
    [InlineData("Model.g.cs", "")]
    [InlineData("Thing.designer.cs", "")]
    public async Task GeneratedCode_IsStillAnalyzed(string path, string header)
    {
        // The analyzer used to call ConfigureGeneratedCodeAnalysis(None) while the CLI's ScanEngine walked
        // every tree, so identical crypto was a finding in the CBOM and silent in the editor. Crypto really
        // does live in generated sources (gRPC/WCF/OpenAPI clients, EF migrations), and the header-only case
        // is the worst of the three: nothing in the filename tells the user why there is no squiggle.
        string source = header + """
            using System.Security.Cryptography;

            public static class Generated
            {
                public static RSA MakeKey() => RSA.Create(2048);
                public static byte[] Legacy(byte[] d) => MD5.HashData(d);
            }
            """;

        var ids = (await AnalyzerHarness.RunAsync(source, path)).Select(d => d.Id).ToHashSet();

        Assert.Contains("CBOM0002", ids);
        Assert.Contains("CBOM0010", ids);
    }

    [Fact]
    public void RuleFailureDescriptor_IsRegistered()
    {
        // ReportDiagnostic throws ArgumentException for an unregistered id, which surfaces as an AD0001
        // storm — so registration is what makes the detector-failure path usable at all.
        DiagnosticDescriptor failure = Assert.Single(
            new CryptoDiagnosticAnalyzer().SupportedDiagnostics, d => d.Id == "CBOM9999");
        Assert.Equal(DiagnosticSeverity.Warning, failure.DefaultSeverity);
    }

    [Fact]
    public async Task CleanCode_ProducesNoWarnings()
    {
        // Negative case: modern authenticated encryption with a generated key must not raise any warning.
        const string clean = """
            using System.Security.Cryptography;

            public static class Safe
            {
                public static byte[] Hash(byte[] d) => SHA384.HashData(d);
                public static (byte[], byte[]) Encrypt(byte[] data, byte[] nonce)
                {
                    using var aes = new AesGcm(RandomNumberGenerator.GetBytes(32), 16);
                    var ct = new byte[data.Length];
                    var tag = new byte[16];
                    aes.Encrypt(nonce, data, ct, tag);
                    return (ct, tag);
                }
            }
            """;

        var warnings = (await AnalyzerHarness.RunAsync(clean))
            .Where(d => d.Severity == DiagnosticSeverity.Warning)
            .ToList();

        Assert.Empty(warnings);
    }
}

/// <summary>
/// Guards the analyzer's Roslyn floor. Roslyn emits CS9057 and SKIPS any analyzer whose
/// Microsoft.CodeAnalysis assembly reference is newer than the running compiler, so a pinned-too-high
/// reference silently disables every CBOM rule on older-but-supported hosts rather than failing loudly.
/// A 4.11 pin cost .NET SDK 8.0.1xx-3xx and VS 2022 17.8-17.10.
///
/// This asserts the assembly reference itself — the exact value the compiler compares — because a build
/// against a floor compiler cannot be staged reliably: Microsoft.Net.Compilers.Toolset does not displace
/// the SDK's own csc for this kind of probe, so that test would pass no matter what the pin said.
/// </summary>
public class AnalyzerRoslynFloorTests
{
    /// <summary>Keep in sync with the analyzer csproj, its README, and docs/COMPATIBILITY.md.</summary>
    private static readonly Version DocumentedFloor = new(4, 8, 0, 0);

    [Fact]
    public void AnalyzerAssembly_DoesNotReferenceARoslynNewerThanTheDocumentedFloor()
    {
        var referenced = typeof(CryptoDiagnosticAnalyzer).Assembly
            .GetReferencedAssemblies()
            .Where(a => a.Name is not null && a.Name.StartsWith("Microsoft.CodeAnalysis", StringComparison.Ordinal))
            .ToList();

        Assert.NotEmpty(referenced);
        foreach (System.Reflection.AssemblyName reference in referenced)
            Assert.True(
                reference.Version <= DocumentedFloor,
                $"{reference.Name} {reference.Version} exceeds the documented Roslyn floor {DocumentedFloor}. "
                + "Hosts on the floor would report CS9057 and skip the analyzer entirely, disabling every "
                + "CBOM rule. Either lower the reference or raise the floor everywhere it is documented.");
    }
}
