import * as vscode from 'vscode';

const WORKFLOW = `# Cryptographic Bill of Materials — PQC risk gate
# Generated by the PostQuantum CBOM VS Code extension.
name: CBOM

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read
  security-events: write   # upload SARIF to code scanning

jobs:
  cbom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - uses: systemslibrarian/PostQuantum.CryptographicBillOfMaterials@v1
        with:
          target: .
          formats: cyclonedx,sarif,markdown,summary
          profile: general
          # Warn on PRs, gate the main branch on new High+ findings.
          fail-on: \${{ github.event_name == 'pull_request' && 'none' || 'high' }}
`;

/** Write a ready-to-run CBOM GitHub Actions workflow into the workspace, without clobbering an existing one. */
export async function addGitHubAction(workspaceRoot: string): Promise<void> {
  const dir = vscode.Uri.file(`${workspaceRoot}/.github/workflows`);
  const file = vscode.Uri.joinPath(dir, 'cbom.yml');

  try {
    await vscode.workspace.fs.stat(file);
    const choice = await vscode.window.showWarningMessage(
      '.github/workflows/cbom.yml already exists. Overwrite it?', 'Overwrite', 'Cancel');
    if (choice !== 'Overwrite') {
      return;
    }
  } catch {
    // Does not exist yet — good.
  }

  await vscode.workspace.fs.createDirectory(dir);
  await vscode.workspace.fs.writeFile(file, Buffer.from(WORKFLOW, 'utf8'));
  const doc = await vscode.workspace.openTextDocument(file);
  await vscode.window.showTextDocument(doc);
  vscode.window.showInformationMessage('Added .github/workflows/cbom.yml');
}
